################################################################################
# File name: vivado_wc_pre.tcl
# Purpose  : This is an internal file that is auto generated by Vivado to source
#            the user tcl file.
################################################################################
open_project "D:/FPGA/Xilinx/Projects/RFID/RFID.xpr"
set rc [catch {
  source -notrace "C:/Users/guysh/AppData/Roaming/Xilinx/Vivado/simulate.tcl"
} result]
if {$rc} {
  puts "$result"
  puts "ERROR: Script failed:\"C:/Users/guysh/AppData/Roaming/Xilinx/Vivado/simulate.tcl\""
}
close_project
